# Generated by Django 4.2.3 on 2023-07-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_conta_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa Econômica'), ('BR', 'Bradesco'), ('ST', 'Santander')], max_length=2),
        ),
    ]
