# Generated by Django 4.2.3 on 2023-07-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_conta_banco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='descricao',
        ),
    ]
